CREATE ROLE puipr LOGIN PASSWORD 'puiprpass';
ALTER DATABASE puiprdb OWNER TO puipr;
GRANT USAGE ON SCHEMA public TO puipr;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO puipr;